### ISSUE TITLE
New user. Can I help with feedback?

### ISSUE THREAD

**Issue by LeeFarm11** [britkat1980/ha-addons#1]
Hi. I have installed Beta and I have some data. 3 phase Gen 3 inverter plus 6 batteries. Some of the numbers look wrong - Battery Power readings seem 10x too high. Many errors in Log. How can I support you with data?
![image](https://github.com/britkat1980/ha-addons/assets/169047365/be10e8bf-7b8f-4582-bfeb-ada7791e41ba)
![image](https://github.com/britkat1980/ha-addons/assets/169047365/aef41294-89cf-4b70-af04-5ce6839d2e94)
![image](https://github.com/britkat1980/ha-addons/assets/169047365/944c6276-b27d-47af-a6a2-b538f58ca2bb)

**Comment by britkat1980** [comment]
Thanks, let me know what data points seem wrong and I'll look into them.

Regarding the errors, it seems that the inverter network comms is not stable. Perhaps the vast amounts of register sets requires a longer (than 3s) timeout period?

**Comment by LeeFarm11** [comment]
Hi. Sorry I can't comment on the timeout. This is very new to me. I stopped the GivTCP add-on and run only this beta add-on. Is that correct? 
Is there some way I can send you all the data you need in one hit?
There is loads of Battery data also now appeared in the Overview, but all the reading are 0.0C or 0V for all 24 cells in all 6 batteries.
<img width="298" alt="image" src="https://github.com/britkat1980/ha-addons/assets/169047365/183b983f-ceec-4bcc-a3ff-c9e5c0154bba">
Here are some examples where the Battery Energy readings are 10x too high.
Battery Charge Energy Total kWh 17087 in HA, 1709 in Giv Portal
<img width="226" alt="image" src="https://github.com/britkat1980/ha-addons/assets/169047365/a382452a-88c7-413d-8284-a06d3f653226">
Battery Charge Energy Today kWh 220 in HA, 22.4 in Giv Portal
<img width="226" alt="image" src="https://github.com/britkat1980/ha-addons/assets/169047365/e6cdf4df-ee65-4e9f-b055-1ee8eddb6055">
Battery Discharge Energy Today kWh 133 in HA, 13.3 in Giv Portal
<img width="217" alt="image" src="https://github.com/britkat1980/ha-addons/assets/169047365/7414266a-689d-4d72-93d7-a6a59fdb2d3e">
<img width="239" alt="image" src="https://github.com/britkat1980/ha-addons/assets/169047365/d9fc59e6-43e7-49a7-8454-80634fdc6a94">

**Comment by britkat1980** [comment]
OK, I've added in the (missing) 0.1 scaling factor for the energy stats, try 2.4.261 and see if that's better

**Comment by LeeFarm11** [comment]
Hi. Thanks.
I uninstalled BETA. I installed DEV 2.4.262
Now the kWh readings look better. 
I do not have GivTCP running. I only have GivTCP-DEV running.

But -
Now I have double of everything. I have Entities starting with 'GivTCP' - correct. AND I have full set of entities starting with 'GivInverter' and they are all 'Unavailable'. For example here is the Device 'GivTCP GivTCP Stats'. Note I do not have version 2.4.255 installed.
<img width="208" alt="image" src="https://github.com/britkat1980/ha-addons/assets/169047365/f75be091-7ddb-43df-93c7-3cdfa4cc2bfd">

**Comment by britkat1980** [comment]
You need to make sure that your “HA Prefix” config item is identical in both dev and beta. It defaults to GivTCP. My guess is you changed it to GivInverter on the Beta, but not the Dev.
Change it and then it will match. You will need to delete the old entities once you have done that

**Comment by LeeFarm11** [comment]
I only have GivTCP-DEV running. Not GivTCP and not GivTCP-BETA. Yes when I was running BETA I did change the default name, but after uninstalling, I would have thought the entities would disappear. Lesson learnt. 
427 entities now removed.

I do still have 288 Battery entities showing 0.0C or 0.0V
![image](https://github.com/britkat1980/ha-addons/assets/169047365/c7418e19-2b6c-432b-9602-375587dc6473)

**Comment by britkat1980** [comment]
Ok, let me see if I can look into the zero battery data. How many batteries do you have?

**Comment by LeeFarm11** [comment]
Hi. 6 batteries.

From: britkat1980 ***@***.***>
Reply to: britkat1980/ha-addons ***@***.***>
Date: Friday, 17 May 2024 at 08:29
To: britkat1980/ha-addons ***@***.***>
Cc: LeeFarm11 ***@***.***>, Author ***@***.***>
Subject: Re: [britkat1980/ha-addons] New user. Can I help with feedback? (Issue #1)


Ok, let me see if I can look into the zero battery data. How many batteries do you have?
