### ISSUE TITLE
How do I Install GivTCP Beta in HA?

### ISSUE THREAD

**Issue by Croft5** [britkat1980/ha-addons#10]
I can install the normal GivTCP in HA fine. How do I install the Beta version?
I have joined the Beta channel in HA.

Thanks

**Comment by britkat1980** [comment]
If you have added this repo into the Addon store in HA.
Then just select the Beta addon, install it and then stop the “old” version. Start this one then head to the web page to configure it

**Comment by Croft5** [comment]
Hi,

I am not seeing a beta version to select...

***@***.***

I can see beta versions for other programs but not for GivTCP???

Dave

**Comment by britkat1980** [comment]
So you don’t see this in the addon store?
![IMG_5419](https://github.com/user-attachments/assets/675abdc7-22ad-4cf7-ae63-92e3882d24c7)

Have you added the repo here:
![IMG_5421](https://github.com/user-attachments/assets/32404c6a-2044-4d6b-9c28-d8106b0bad99)

**Comment by Croft5** [comment]
I am using a W11 desktop rather than a phone, but no I do not see what you sent.

I go to the 3 dots in the Add-on Store and can find this repository...

***@***.***

I add that and all I get is the standard GivTCP option, no beta or dev

Dave

**Comment by LeeFarm11** [comment]
You need to add this repository -

https://github.com/britkat1980/ha-addons

**Comment by Croft5** [comment]
Yes, that worked, thanks so much

**Comment by LeeFarm11** [comment]
Welcome aboard. I'm hoping to get up and running with Predbat, but need to get GivTCP working first with the 3 phase Inverter. Seems many teething issues with the 3 phase but hopefully eventually everything will fall into place. Do you have a 3 phase Inverter?

**Comment by Croft5** [comment]
No, one phase is enough 😊
All the very best with your setup.
I have just installed GivTCP, now for the setup

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Croft5** [comment]
All working now 😊

Thanks, Dave
