### ISSUE TITLE
Missing entities after upgrading from 2.4.9 to 3.0.0

### ISSUE THREAD

**Issue by ashenshugarRET** [britkat1980/ha-addons#18]
After upgrading my GivTCP HA Add-On from version 2.4.9 installed from the original repo to version 3.0.0 from this repo I have noticed the battery_power_mode and enable_discharge entities are no longer available in my dashboard. Is this expected? Have they been replaced with new equivalent, differently named entities or is this a bug?

**Comment by britkat1980** [comment]
battery_power_mode is now called "eco_mode" to become consistent with the portal and "enable_discharge" has been depreciated as it serves no real function (all it did was force the battery reserve to 100%)
