### ISSUE TITLE
GivTCP Inverter Details Dev 2.4.270

### ISSUE THREAD

**Issue by LeeFarm11** [britkat1980/ha-addons#3]
Hi.
In the GivTCP Inverter Details section I have some strange readings. I have a few Unknowns -

GivTCP Battery Priority
GivTCP DC Status
GivTCP Inverter Time
GivTCP System Mode

GivTCP Inverter Firmware is showing the wrong version. Showing D0.0-A0.0 but I have
![image](https://github.com/britkat1980/ha-addons/assets/169047365/e2ab153a-a572-40d3-9994-bd1a1bce89c6)

GivTCP Inverter Type shows as Gen 1 - Hybrid_3ph but I believe it is Gen 3.

**Comment by britkat1980** [comment]
Given the number of issues it would be great to connect directly to troubleshoot, are you able to setup a VPN and allow me access?? If you're in the fb group then DM me there

**Comment by LeeFarm11** [comment]
In 2.4.284 this section - GivTCP Inverter Details - has disappeared.

**Comment by britkat1980** [comment]
It’s now under the serial number of the inverter, matching the new naming convention for batteries

**Comment by LeeFarm11** [comment]
Ah. Thanks. Yes I found it. 

Still have the same 4 Unknowns.
Software version still shows D0.0-A0.0
Inverter Type still shows Gen1
