### ISSUE TITLE
GivTCP Power Frequencies not correct.

### ISSUE THREAD

**Issue by LeeFarm11** [britkat1980/ha-addons#6]
In 2.4.280 Frequencies are showing around 5Hz instead of around 50Hz.

![image](https://github.com/britkat1980/ha-addons/assets/169047365/81caaded-9059-41b4-bdb4-9b71bf43b156)

**Comment by britkat1980** [comment]
Thanks have changed scaling and will correct in next release

**Comment by LeeFarm11** [comment]
Fixed in 2.4.285.
Thanks
