### ISSUE TITLE
Frequency error?

### ISSUE THREAD

**Issue by danceresort** [britkat1980/ha-addons#9]
I think the Freqency is wrong on the "GivTCP3 Meter Details Frequency" sensor.givtcp3_gw<S/N>_frequency sensor? I used to monitor this to be 50 (to check for any power cut), maybe the decimal  is in the wrong place?

![image](https://github.com/user-attachments/assets/35738575-9bc1-495a-a40d-51eaccd6a68c)

I have 2 AIO with Gateway if that helps, so now monitoring on the GW rather than the AIO itself.

**Comment by britkat1980** [comment]
This is a fw bug in the gateway. GivEnergy are aware and will be fixing in future release.
